version: '3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.0
    container_name: elasticsearch
    environment:
      - cluster.name=sample-elasticsearch-cluster
      - discovery.type=single-node
      - xpack.security.enabled=false
    volumes:
      - elasticsearch_volume:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - elasticsearch_network

  kibana:
    image: docker.elastic.co/kibana/kibana:6.4.0
    container_name: kibana
    environment:
      - server.port=5601
      - elasticsearch.url=http://elasticsearch:9200
      - xpack.security.enabled=false
    ports:
      - "5601:5601"
    networks:
      - elasticsearch_network
    depends_on:
      - elasticsearch

volumes:
  elasticsearch_volume:
    driver: local

networks:
  elasticsearch_network:
